version: '2'

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: ${DOCKER_NETWORK_NAME}